CREATE EXTENSION pgcrypto;

CREATE TABLE IF NOT EXISTS users (
id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY NOT NULL,
email TEXT NOT NULL UNIQUE,
chat_id TEXT NOT NULL,
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS origins (
id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY NOT NULL,
origin TEXT NOT NULL,
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS sessions (
id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY NOT NULL,
user_id UUID REFERENCES users(id),
origin_id UUID REFERENCES origins(id));
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

CREATE TABLE IF NOT EXISTS codes (
id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY NOT NULL,
code TEXT,
attempts INT,
user_id UUID REFERENCES users(id),
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS permissions (
id SMALLSERIAL PRIMARY KEY,
user_id UUID REFERENCES users(id),
origin_id UUID REFERENCES origins(id),
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
